# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: "jose" # < TU_USUARIO@hodl.ar

# NOSTR Settings
# nostr: # Sin el # adelante
   npub: "npub1n7sap6xxc7epgcp7vcp8q73stm87fe3p8k22hh9ccskffg3vzapq6eehzk" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: "Links | José Milano" # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: "José Milano" # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/jjmilanof1/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/jjmilano
    
  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://www.linkedin.com/in/jose-milano-235631111/ # Link a donde redireccionará al hacer click

# - title: Github
#   icon: github
#   url: https://github.com/TU-USUARIO

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
